[theme]
primaryColor = "#1E7F4F"             # Strong forest green (buttons, accents)
backgroundColor = "#EDF5EC"          # Slightly darker green-tinted background
secondaryBackgroundColor = "#FFFFFF" # Clean white for widgets/cards
textColor = "#172B1B"                # Dark green-black for readability
font = "sans serif"


