[theme]
primaryColor = "#1E7F4F"             # Button & highlight
backgroundColor = "#F4FFF8"          # App background
secondaryBackgroundColor = "#FFFFFF" # Widgets/cards
textColor = "#1E392A"                # Primary text
font = "sans serif"                  # Clean default font

